# base: immagine Node (contiene node/npm)
FROM node:20.11.1

# aggiorna apt e installa git, go, python3 e pip; rimuove cache apt per immagine più leggera
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    git \
    golang-go \
    python3 \
    python3-pip \
 && rm -rf /var/lib/apt/lists/*